In [1]:
import pandas as pd

In [3]:
df_inferido = pd.read_csv("potencias.csv")
df_real = pd.read_csv("../prediccion-horno/generados/inicial/split_0.csv")

In [9]:
df_real['potencia']

0     102.034000
1     104.364000
2     112.542000
3      98.498800
4     102.823000
5     111.598000
6     111.506000
7     110.020000
8      99.337000
9       0.000320
10      0.001070
11      3.480530
12     55.483000
13     62.619100
14     78.238900
15     91.448100
16     98.934200
17     97.804900
18     89.027400
19     93.006200
20    104.051000
21     98.977300
22    104.969000
23    102.964000
24    103.478000
25     95.532900
26    111.018000
27     99.668000
28    102.620000
29    100.909000
30    101.879000
31    107.101000
32    111.564000
33    115.792000
34    105.105000
35    102.366000
36    103.814000
37    108.083000
38    105.526000
39     90.772900
40     91.236200
41     89.030000
42     85.089900
43     90.908500
44     92.250200
45     75.560700
46     74.649500
47     82.685800
48     54.118900
49      0.001304
50      0.000756
51      0.001066
52      0.001271
53      0.001072
54      0.001289
Name: potencia, dtype: float64

In [18]:
df_merged = pd.concat([df_real['potencia'], df_inferido], ignore_index=True, axis=1)
df_merged = df_merged.rename(columns={0: "potencia_real", 1: "potencia_inferida"})

In [19]:
df_merged

    potencia_real  potencia_inferida
0      102.034000                100
1      104.364000                110
2      112.542000                120
3       98.498800                130
4      102.823000                128
5      111.598000                118
6      111.506000                128
7      110.020000                118
8       99.337000                116
9        0.000320                126
10       0.001070                136
11       3.480530                146
12      55.483000                156
13      62.619100                154
14      78.238900                164
15      91.448100                154
16      98.934200                144
17      97.804900                154
18      89.027400                154
19      93.006200                144
20     104.051000                154
21      98.977300                144
22     104.969000                154
23     102.964000                159
24     103.478000                159
25      95.532900                169
26     111.018000                179
27      99.668000                189
28     102.620000                179
29     100.909000                189
30     101.879000                189
31     107.101000                199
32     111.564000                209
33     115.792000                219
34     105.105000                229
35     102.366000                239
36     103.814000                237
37     108.083000                247
38     105.526000                257
39      90.772900                267
40      91.236200                277
41      89.030000                287
42      85.089900                277
43      90.908500                287
44      92.250200                292
45      75.560700                302
46      74.649500                312
47      82.685800                302
48      54.118900                312
49       0.001304                322
50       0.000756                332
51       0.001066                342
52       0.001271                352
53       0.001072                362
54       0.001289                367